name: Report test coverage

on:
  push:
    branches:
      - master

jobs:
  report-test-coverage:
    name: Report test coverage (Node.js ${{ matrix.node-version }} - ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [16.0.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up project, install dependencies
        run: npm ci

      - name: Run test with coverage and report it to codecov.io
        run: npm run report-coverage
